language: swift
osx_image: xcode10.2
cache: bundler
xcode_project: web3swift.xcworkspace
xcode_scheme: web3swift-iOS
xcode_destination: platform=iOS Simulator, OS=12.2, name=iPhone X
before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
before_script:
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds
script:
  - xcodebuild -scheme web3swift -project web3swift.xcodeproj -sdk iphonesimulator build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
