os: osx
language: swift
osx_image: xcode10.2

branches:
  only: 
    - master
stages:
  - lint
  - carthage
  - swiftpm
  - test
jobs:
  include:
    - &pod
      stage: lint
      osx_image: xcode8.3
      env: SWIFT=3.1
      cache:
        - cocoapods
        - directories:
          - Carthage
      before_install:
        gem install cocoapods --prerelease --version 1.7.0.beta.3
      install:
        carthage bootstrap --no-build PromiseKit
      script: |
        cd Carthage/Checkouts/PromiseKit
        mv .github/PromiseKit.podspec .
        rm -rf Extensions/Alamofire/Sources
        cp -R ../../../Sources Extensions/Alamofire
        pod lib lint --subspec=PromiseKit/Alamofire --fail-fast --swift-version=$SWIFT
    - <<: *pod
      osx_image: xcode9.2
      env: SWIFT=3.2
    - <<: *pod
      osx_image: xcode9.4
      env: SWIFT=3.3
    - <<: *pod
      osx_image: xcode10.1
      env: SWIFT=3.4
    - <<: *pod
      osx_image: xcode9.2
      env: SWIFT=4.0
    - <<: *pod
      osx_image: xcode9.4
      env: SWIFT=4.1
    - <<: *pod
      osx_image: xcode10.1
      env: SWIFT=4.2
    - <<: *pod
      osx_image: xcode10.2
      env: SWIFT=4.3
    - <<: *pod
      osx_image: xcode10.2
      env: SWIFT=5.0
      
    - &carthage
      stage: carthage
      osx_image: xcode9.2
      script: |
        carthage bootstrap --cache-builds
        sed -i '' "s/SWIFT_TREAT_WARNINGS_AS_ERRORS = NO;/SWIFT_TREAT_WARNINGS_AS_ERRORS = YES;/" *.xcodeproj/project.pbxproj
        carthage build --no-skip-current
      cache:
        directories:
        - Carthage
    - <<: *carthage
      osx_image: xcode9.4
    - <<: *carthage
      osx_image: xcode10.1
    - <<: *carthage
      osx_image: xcode10.2

    - &swiftpm
      stage: swiftpm
      name: Xcode 8.3 / SwiftPM
      os: osx
      osx_image: xcode8.3
      language: objective-c
      script: swift build
    - <<: *swiftpm
      name: Xcode 9.4 / SwiftPM
      osx_image: xcode9.4
    - <<: *swiftpm
      name: Xcode 10.1 / SwiftPM
      osx_image: xcode10
    - <<: *swiftpm
      name: Xcode 10.2 / SwiftPM
      osx_image: xcode10.2

    - &test
      stage: test
      xcode_scheme: PMKAlamofire
      xcode_project: PMKAlamofire.xcodeproj
      xcode_destination: 'platform=macOS'
      cache:
        directories:
        - Carthage
      before_install:
        carthage bootstrap --cache-builds --no-use-binaries
    - <<: *test
      xcode_destination: 'platform=iOS Simualtor,OS=12.2,name=iPhone SE'
    - <<: *test
      xcode_destination: 'platform=tvOS Simulator,OS=12.2,name=Apple TV'
